CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE todo_items
(
    id VARCHAR DEFAULT uuid_generate_v4() NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    title VARCHAR NOT NULL,
    status VARCHAR NOT NULL,
    CONSTRAINT todo_items_pk PRIMARY KEY (id)
);
