name: Api Unit

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/api/**'
  pull_request:
    paths:
      - 'packages/api/**'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_DB: testing
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: --health-cmd pg_isready
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.7.0
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install
        run: |
          npm install -g npm@latest
          npm install
      - name: Test
        run: |-
          npm run ci:api
        env:
          SECRET_KNEX_CONNECTION: postgres://postgres:postgres@localhost:5432/testing
